### ISSUE TITLE
Path too long exception winpeasx64.exe

### ISSUE THREAD

**Issue by Donovoi** [carlospolop/PEASS-ng#309]
If you are going to suggest something, please remove the following template. 

#### Issue description
Path too long exception when running winpeasx64.exe (non ofs) 20220901

#### Steps to reproduce the issue

1.  Install a fresh version of windows 11 insiders
2. download and run winpeas in windows terminal preview - using command prompt as the terminal

#### Which parameters did you use for executing the script and how did you execute it?
none

#### If winpeas, did you use a clean or obfuscated winpeas, and for which architecture?
clean x64

#### Is there any AV / Threat protection in the system?
no disabled by gpo - but im finding defender is repairing it self even when it is disabled

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)

Microsoft Windows [Version 10.0.25193.1000]   
#### Please, indicate the check that is failing and add a screenshot showing the problem
```
  - Creating files/directories list for search...
Error while creating directory list: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at winPEAS.Helpers.Search.SearchHelper.<>c__DisplayClass9_0.<GetFilesFast>b__2(FileInfo f)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at winPEAS.Helpers.Search.SearchHelper.<>c__DisplayClass9_0.<GetFilesFast>b__0(DirectoryInfo d)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at winPEAS.Helpers.Search.SearchHelper.GetFilesFast(String folder, String pattern, HashSet`1 excludedDirs, Boolean isFoldersIncluded)
   at winPEAS.Helpers.Search.SearchHelper.CreateSearchDirectoriesList()
   at winPEAS.Checks.Checks.CreateDynamicLists()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at winPEAS.Helpers.Search.SearchHelper.<>c__DisplayClass9_0.<GetFilesFast>b__2(FileInfo f)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at winPEAS.Helpers.Search.SearchHelper.<>c__DisplayClass9_0.<GetFilesFast>b__0(DirectoryInfo d)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at winPEAS.Helpers.Search.SearchHelper.<>c__DisplayClass9_0.<GetFilesFast>b__2(FileInfo f)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

```

Happens again at ` Searching executable files in non-default folders with write (equivalent) permissions (can be slow)`

```

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at winPEAS.Helpers.Search.SearchHelper.<>c__DisplayClass9_0.<GetFilesFast>b__2(FileInfo f)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at winPEAS.Helpers.Search.SearchHelper.<>c__DisplayClass9_0.<GetFilesFast>b__0(DirectoryInfo d)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at winPEAS.Helpers.Search.SearchHelper.GetFilesFast(String folder, String pattern, HashSet`1 excludedDirs, Boolean isFoldersIncluded)
   at winPEAS.Checks.FilesInfo.PrintExecutablesInNonDefaultFoldersWithWritePermissions()
   at winPEAS.Helpers.CheckRunner.Run(Action action, Boolean isDebug, String description)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at winPEAS.Checks.Checks.RunChecks(Boolean isAllChecks, Boolean wait)
   at winPEAS.Checks.Checks.<>c__DisplayClass26_0.<Run>b__1()
   at winPEAS.Helpers.CheckRunner.Run(Action action, Boolean isDebug, String description)
   at winPEAS.Checks.Checks.Run(String[] args)
   at winPEAS.Program.Main(String[] args)

```
Then program crashes

#### How did you expect it to work?
no stack trace and no error

#### Additional details / screenshot

Obviously we can fix this via registry, should we check for this limit before running the script? Make adjustments to handle it or Maybe just warn the user  and/or direct them on how to change this value?

**Comment by carlospolop** [comment]
Hi @Donovoi,

Sorry for the waiting.
As you suggests, it looks like modifying a key in the registry will fix this (https://stackoverflow.com/questions/8745215/best-way-to-resolve-file-path-too-long-exception). However, you need high privileges to modify that key do you know any other way?

Moreover, I tried to fix this issue with https://github.com/carlospolop/PEASS-ng/commit/f86e301a1b16b989ab4f802dd3a03781216c1620 but I didn't have that error so I don't know if the patch will work.
Could you please test the latest version (it will be build a couple of hours) and check if the errors still appear? And if they do could you send a PR improving the patch?
Thank you

**Comment by Donovoi** [comment]
Awesome thank you @carlospolop I'll work on this tonight. I had a look at this https://c-nergy.be/blog/?p=15339 I'm thinking we can change the path somehow using DOS Device Syntax. Have look here https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#traditional-dos-paths

I'll let you know how I go

**Comment by carlospolop** [comment]
Hi @Donovoi,

Any news on this? Will you have time to try to fix this?

**Comment by Donovoi** [comment]
Hey Carlos!

Sorry I didn't reply, I have been working on a solution in my free time. I have found a few possible solutions but need to double check - Did you want to target the same .net framework? I think atm it is 4.5.2 - If we target a newer one, it may be easier (at least for me) to find a good solution. 

I'm thinking along the lines of using cswin32/pinvoke/dllimport/ or some sort of source generation to import a c/c++ function that is not affected by this limit. 

let me know what you think

**Comment by carlospolop** [comment]
If possible I would like to keep the same .Net version, if possible. If not, just send the PR using a different version. In this case it would be interesting if somehow we could make winpeas work as it's currently working if the newest version isn't installed and with the fix if the version is installed (but I don't know how complex this could be)

**Comment by Donovoi** [comment]
Ok all good. I've got a solution using WIN32_FIND_DATA struct, just need to work out how to properly implement it.

**Comment by godylockz** [comment]
I also saw this issue. Here is the stacktrace. It has to do with nested junctions in this case.... I haven't run into this issue before but definitely will hit recursion limit:
```text
- Creating files/directories list for search...
The path C:\Users\Administrator\AppData\Local\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\IconCache.db is too large, try to enable LongPaths in the registry (no more warning about this will be shown)
Error while creating directory list: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at ib.a.g(FileInfo A_0)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at ib.a.h(DirectoryInfo A_0)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at ib.a(String A_0, String A_1, HashSet`1 A_2, Boolean A_3)
   at ib.h()
   at winPEAS.Checks.Checks.d()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at ib.a.g(FileInfo A_0)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at ib.a.h(DirectoryInfo A_0)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at ib.a.g(FileInfo A_0)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at ib.a.g(FileInfo A_0)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---
```

**Comment by musicmancorley** [comment]
I ran in to this as well on a freshly compiled winpeas.  even with the registry setting it would still crash.  For what it's worth, I was able to avoid this issue by changing the target .NET framework to 4.7.2.  anything < 4.6.1 had issues with legacy filepath limitations and 4.7.2 seems to ignore any filepath length restrictions.  running great now with no unhandled exceptions!  Great tool btw

**Comment by musicmancorley** [comment]
hey Carlos, yes that is correct.  Based on my testing with windows 11 and .Net 4.7.2  even with NOT setting the registry setting for longpath filenames, Winpeas will continue and not throw an unhandled exception.  This is the only message I see if I intentionally don't allow longfilenames via windows registry.  Otherwise, Winpeas runs just fine:
![image](https://user-images.githubusercontent.com/19558280/231803062-a36dde9f-7751-4974-90e8-88bf5101d878.png)

**Comment by Donovoi** [comment]
#350 fixed this issue

**Comment by asadzz** [comment]
I'm using the latest build https://github.com/carlospolop/PEASS-ng/releases/tag/20230618-1fa055b6 and I'm still getting the same error for 64 bit winpeas

����������͹ Searching executable files in non-default folders with write (equivalent) permissions (can be slow)
```

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'AlphaFS, Version=2.2.0.0, Culture=neutral, PublicKeyToken=4d31a58f7d7ad5c9' or one of its dependencies. The system cannot find the file specified.
   at ib.a(String A_0, String A_1, HashSet`1 A_2, Boolean A_3)
   at ik.g()
   at h5.a(Action A_0, Boolean A_1, String A_2)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at winPEAS.Checks.Checks.a(Boolean A_0, Boolean A_1)
   at winPEAS.Checks.Checks.b.c()
   at h5.a(Action A_0, Boolean A_1, String A_2)
   at winPEAS.Checks.Checks.a(String[] A_0)
   at winPEAS.Program.Main(String[] args)
```

**Comment by carlospolop** [comment]
Hi @asadzz this was fixed at the end of July, please use a more recent release and let me know if you find the same problem
